name: Deploy AWS Infrastructure with CloudFormation Template

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      run: |
        pwd
        ls -lart

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file ./infrastructure/cloudformation-template.yaml \
          --stack-name aws-pubsub-pattern-stack \
          --capabilities CAPABILITY_NAMED_IAM
